name: "Terraform"

on: [push]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY}}
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: Initialize
        run: terraform init
      - name: validate
        run: terraform validate
      - name: format
        run: terraform fmt -check
      - name: plan
        run: terraform plan